Document: fcmp
Title: Debian fcmp Manual
Author: <insert document author here>
Abstract: This manual describes what fcmp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fcmp/fcmp.sgml.gz

Format: postscript
Files: /usr/share/doc/fcmp/fcmp.ps.gz

Format: text
Files: /usr/share/doc/fcmp/fcmp.text.gz

Format: HTML
Index: /usr/share/doc/fcmp/html/index.html
Files: /usr/share/doc/fcmp/html/*.html
